POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlVzZXJzMiIsImlkIjoiNjVmYzZmNjJiZDBiZTRhNjE3NGZjNDkwIiwiaWF0IjoxNzExMTU2ODQyLCJleHAiOjE3MTExNjA0NDJ9.BEsVL663t8dnTcUI6fuoYl0A00OTvMeqy6CRQUuYtY0

{
    "title": "Matias en busca de un trabajo n°28",
    "author": "Matias",
    "url": "wwww.matias.com",
    "likes": "7",
    "userId" : "65fc6e95bd0be4a6174fc48c"
}