POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlVzZXJzMSIsImlkIjoiNjVmYzZlOTViZDBiZTRhNjE3NGZjNDhjIiwiaWF0IjoxNzExMzIxMjY2LCJleHAiOjE3MTEzMjQ4NjZ9.A9nuiAuY_1OUTbC_kPgJGtBudpagvIkYITDYCplDqnw

{
    "title": "Matias en busca de un trabajo n°30",
    "author": "Matias",
    "url": "wwww.matias.com",
    "likes": "7"
}